import { NextRequest, NextResponse } from 'next/server'

const mockJobs = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    salary: '$160,000 - $220,000',
    type: 'Hybrid',
    description: `Stripe is looking for a Senior Software Engineer to join our Payments Infrastructure team. You'll work on the core systems that process hundreds of billions of dollars annually for millions of businesses worldwide.\n\nIn this role, you'll design and build highly reliable, distributed systems that handle payments at massive scale. You'll collaborate with world-class engineers on hard technical problems that have real business impact.\n\nWe value pragmatism, clear communication, and a bias toward action. Our team ships fast and takes ownership of their work from design through production.`,
    requirements: [
      '5+ years of professional software engineering experience',
      'Strong proficiency in Go, Ruby, or Java',
      'Experience with distributed systems and microservices',
      'Deep understanding of databases and data modeling',
      'Track record of leading technical projects end-to-end',
      'Experience with API design and developer tooling',
    ],
    tags: ['Go', 'Distributed Systems', 'Payments', 'API'],
    matchScore: 94,
    postedDate: '2024-01-15',
    logo: 'S',
    logoColor: 'bg-blue-600',
  },
  {
    id: '2',
    title: 'Product Manager, Growth',
    company: 'Notion',
    location: 'New York, NY',
    salary: '$140,000 - $180,000',
    type: 'Remote',
    description: `Notion is hiring a Product Manager to lead our Growth team. You'll own key metrics around user activation, retention, and expansion across our 30M+ user base.\n\nYou'll work at the intersection of product, data, and marketing to identify growth opportunities and run experiments that move the needle. This is a high-impact role with significant autonomy.\n\nWe're looking for someone who combines analytical rigor with product intuition and can move quickly from insight to execution.`,
    requirements: [
      '4+ years of product management experience',
      'Experience running A/B tests and interpreting results',
      'Strong SQL skills and comfort with data analysis',
      'Track record of driving measurable growth metrics',
      'Excellent written and verbal communication',
      'Experience with PLG (product-led growth) strategies',
    ],
    tags: ['Growth', 'PLG', 'Analytics', 'B2B SaaS'],
    matchScore: 88,
    postedDate: '2024-01-14',
    logo: 'N',
    logoColor: 'bg-gray-700',
  },
  {
    id: '3',
    title: 'Senior Data Scientist',
    company: 'Airbnb',
    location: 'San Francisco, CA',
    salary: '$150,000 - $200,000',
    type: 'Hybrid',
    description: `Airbnb is seeking a Senior Data Scientist to join the Trust & Safety team. You'll develop machine learning models to detect fraud and improve platform safety for 150M+ guests and 4M+ hosts.\n\nYou'll work with petabytes of behavioral data to build models that make real-time decisions at scale. This is a high-stakes domain where your work directly protects our community.\n\nYou'll collaborate closely with engineers, policy teams, and operations to understand the full picture and design effective solutions.`,
    requirements: [
      '5+ years of data science or ML experience',
      'Expert-level Python (pandas, scikit-learn, PyTorch)',
      'Experience with large-scale data processing (Spark, Hive)',
      'Strong background in statistical modeling and ML algorithms',
      'Experience with fraud detection or anomaly detection',
      'Ability to communicate complex findings to non-technical stakeholders',
    ],
    tags: ['Python', 'Machine Learning', 'Fraud Detection', 'SQL'],
    matchScore: 91,
    postedDate: '2024-01-13',
    logo: 'A',
    logoColor: 'bg-red-600',
  },
  {
    id: '4',
    title: 'Marketing Manager, Brand',
    company: 'Linear',
    location: 'Remote',
    salary: '$110,000 - $145,000',
    type: 'Remote',
    description: `Linear is looking for a Marketing Manager to own our brand and content strategy. You'll define how we show up in the world and tell the story of why developers and product teams choose Linear.\n\nWe're a product-led company with a strong brand reputation. You'll work closely with our CEO and design team to produce content that resonates with software teams at the best companies.\n\nThis is a creative and strategic role for someone who cares deeply about craft and can operate with significant autonomy.`,
    requirements: [
      '4+ years of B2B marketing experience',
      'Strong writing and storytelling ability',
      'Experience managing brand guidelines and voice',
      'Track record of creating content that drives developer adoption',
      'Comfortable with analytics and measuring content performance',
      'Experience in SaaS or developer tools preferred',
    ],
    tags: ['Brand', 'Content', 'B2B', 'SaaS'],
    matchScore: 72,
    postedDate: '2024-01-12',
    logo: 'L',
    logoColor: 'bg-violet-600',
  },
  {
    id: '5',
    title: 'Senior UX Designer',
    company: 'Figma',
    location: 'San Francisco, CA',
    salary: '$145,000 - $195,000',
    type: 'Hybrid',
    description: `Figma is hiring a Senior UX Designer to work on our core editor experience. You'll shape the product used by millions of designers worldwide, working on the tools they rely on every day.\n\nThis role requires someone who can operate at multiple levels — from high-level strategy to pixel-perfect execution. You'll partner closely with engineers and PMs to ship experiences that feel effortless.\n\nWe care deeply about design quality and you'll be joining a team that pushes the craft forward.`,
    requirements: [
      '6+ years of product design experience',
      'Portfolio showing complex, shipped product work',
      'Expert-level Figma skills (obviously)',
      'Experience designing for power users and complex workflows',
      'Strong interaction design and systems thinking',
      'Ability to drive alignment across cross-functional teams',
    ],
    tags: ['Product Design', 'UX', 'Figma', 'Design Systems'],
    matchScore: 85,
    postedDate: '2024-01-11',
    logo: 'F',
    logoColor: 'bg-pink-600',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'Vercel',
    location: 'Remote',
    salary: '$130,000 - $175,000',
    type: 'Remote',
    description: `Vercel is seeking a DevOps Engineer to help scale our global edge infrastructure that serves billions of requests per day. You'll work on the systems that make the web faster for developers everywhere.\n\nYou'll manage Kubernetes clusters, CI/CD pipelines, and cloud infrastructure across AWS, GCP, and our own edge network. This is a high-impact role at a company obsessed with performance.\n\nWe move fast and you'll have significant ownership over critical systems.`,
    requirements: [
      '4+ years of DevOps or Site Reliability Engineering experience',
      'Expert knowledge of Kubernetes and container orchestration',
      'Strong experience with AWS or GCP',
      'Proficiency with Terraform or Pulumi for IaC',
      'Experience with CI/CD pipelines (GitHub Actions, Jenkins)',
      'Solid networking and security fundamentals',
    ],
    tags: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD'],
    matchScore: 79,
    postedDate: '2024-01-10',
    logo: 'V',
    logoColor: 'bg-gray-900',
  },
  {
    id: '7',
    title: 'Enterprise Sales Representative',
    company: 'Snowflake',
    location: 'New York, NY',
    salary: '$90,000 - $120,000 + Commission',
    type: 'Onsite',
    description: `Snowflake is growing our Enterprise Sales team and looking for driven Account Executives to own Fortune 500 relationships. You'll sell our data cloud platform to CTOs, VPs of Data, and CDOs at large enterprises.\n\nThis is a full-cycle sales role where you'll prospect, demo, negotiate, and close complex six and seven-figure deals. You'll be supported by excellent SE resources and a strong brand.\n\nWe have a proven playbook and unlimited upside for top performers.`,
    requirements: [
      '3+ years of enterprise software sales experience',
      'Track record of consistently exceeding quota',
      'Experience selling to technical buyers (data/engineering leaders)',
      'Comfort with complex, multi-stakeholder sales cycles',
      'Strong presentation and negotiation skills',
      'Experience with Salesforce and modern sales tools',
    ],
    tags: ['Enterprise Sales', 'Data', 'B2B', 'Cloud'],
    matchScore: 65,
    postedDate: '2024-01-10',
    logo: 'S',
    logoColor: 'bg-cyan-600',
  },
  {
    id: '8',
    title: 'Financial Analyst',
    company: 'Robinhood',
    location: 'Menlo Park, CA',
    salary: '$95,000 - $130,000',
    type: 'Hybrid',
    description: `Robinhood is looking for a Financial Analyst to join our FP&A team. You'll support the business by building financial models, analyzing trends, and helping leaders make better decisions with data.\n\nYou'll own key financial reports, support the annual planning process, and do deep-dive analysis on business performance. This is a high-visibility role with direct exposure to senior leadership.\n\nWe're building a more equitable financial system and want people who care about the mission.`,
    requirements: [
      '3+ years of FP&A or investment banking experience',
      'Advanced Excel and financial modeling skills',
      'Experience with SQL for data analysis',
      'Strong presentation and communication skills',
      'Ability to synthesize complex data into clear insights',
      'Experience in fintech or consumer technology preferred',
    ],
    tags: ['FP&A', 'Financial Modeling', 'SQL', 'Fintech'],
    matchScore: 70,
    postedDate: '2024-01-09',
    logo: 'R',
    logoColor: 'bg-emerald-600',
  },
  {
    id: '9',
    title: 'Content Writer, Technical',
    company: 'HashiCorp',
    location: 'Remote',
    salary: '$85,000 - $115,000',
    type: 'Remote',
    description: `HashiCorp is hiring a Technical Content Writer to create documentation, tutorials, and blog posts for our open source tools (Terraform, Vault, Consul, Nomad) used by hundreds of thousands of engineers.\n\nYou'll work with engineering teams to deeply understand our products and translate technical concepts into clear, accurate content that helps developers succeed.\n\nStrong writing skills and genuine interest in infrastructure technology are essential.`,
    requirements: [
      '3+ years of technical writing or developer content experience',
      'Ability to understand and explain complex technical concepts',
      'Experience with developer tools or infrastructure technology',
      'Strong portfolio of technical writing samples',
      'Familiarity with Terraform, Kubernetes, or cloud platforms',
      'Experience with docs-as-code workflows',
    ],
    tags: ['Technical Writing', 'DevOps', 'Developer Relations', 'Open Source'],
    matchScore: 75,
    postedDate: '2024-01-09',
    logo: 'H',
    logoColor: 'bg-purple-600',
  },
  {
    id: '10',
    title: 'Customer Success Manager',
    company: 'Intercom',
    location: 'Chicago, IL',
    salary: '$80,000 - $110,000',
    type: 'Hybrid',
    description: `Intercom is seeking a Customer Success Manager to own relationships with our mid-market customers and drive expansion and retention. You'll work with 50-80 accounts and become a trusted advisor on customer communications strategy.\n\nYou'll conduct QBRs, drive feature adoption, identify expansion opportunities, and work cross-functionally to resolve issues quickly. Customer outcomes are your north star.\n\nWe have an incredible product and a supportive team — this is a great role for someone who loves building relationships and solving problems.`,
    requirements: [
      '3+ years of customer success or account management experience',
      'Track record of hitting retention and expansion targets',
      'Experience with CRM tools (Salesforce, Gainsight)',
      'Strong communication and presentation skills',
      'Ability to manage a large portfolio of accounts',
      'Experience in SaaS preferred',
    ],
    tags: ['Customer Success', 'SaaS', 'Account Management', 'B2B'],
    matchScore: 68,
    postedDate: '2024-01-08',
    logo: 'I',
    logoColor: 'bg-blue-500',
  },
  {
    id: '11',
    title: 'Backend Engineer, Payments',
    company: 'Shopify',
    location: 'Remote',
    salary: '$140,000 - $190,000',
    type: 'Remote',
    description: `Shopify is looking for a Backend Engineer to join the Payments team that processes $200B+ in annual merchant sales. You'll build reliable, scalable payment processing systems that power commerce worldwide.\n\nYou'll work primarily in Ruby and Go, designing APIs and services that handle millions of transactions per day. Reliability and correctness are paramount in this domain.\n\nWe're a remote-first team with people across 30+ countries.`,
    requirements: [
      '5+ years of backend engineering experience',
      'Expert knowledge of Ruby or Go',
      'Experience with payments, fintech, or high-reliability systems',
      'Strong understanding of distributed systems concepts',
      'Experience with SQL databases and query optimization',
      'Track record of building and maintaining production APIs',
    ],
    tags: ['Ruby', 'Go', 'Payments', 'Backend'],
    matchScore: 92,
    postedDate: '2024-01-08',
    logo: 'S',
    logoColor: 'bg-green-600',
  },
  {
    id: '12',
    title: 'Frontend Engineer',
    company: 'Linear',
    location: 'Remote',
    salary: '$130,000 - $180,000',
    type: 'Remote',
    description: `Linear is hiring a Frontend Engineer to work on our native-feeling web application used by tens of thousands of software teams. You'll build interfaces that are fast, beautiful, and delightful to use.\n\nWe obsess over performance and UX — our app loads in under 100ms and uses optimistic updates throughout. You'll work with React, TypeScript, and our custom state management layer.\n\nThis is a senior role where you'll have significant ownership and influence over the product.`,
    requirements: [
      '5+ years of frontend engineering experience',
      'Expert-level React and TypeScript skills',
      'Deep understanding of web performance optimization',
      'Experience with complex state management',
      'Eye for design and attention to UX details',
      'Experience building highly interactive web applications',
    ],
    tags: ['React', 'TypeScript', 'Performance', 'Frontend'],
    matchScore: 96,
    postedDate: '2024-01-07',
    logo: 'L',
    logoColor: 'bg-violet-600',
  },
  {
    id: '13',
    title: 'Full Stack Developer',
    company: 'Retool',
    location: 'San Francisco, CA',
    salary: '$145,000 - $195,000',
    type: 'Onsite',
    description: `Retool is seeking a Full Stack Developer to work on our internal tool building platform used by 5,000+ companies including Amazon, DoorDash, and NBC. You'll build features across the entire stack from React frontends to Node.js backends.\n\nYou'll work on one of the most technically challenging codebases in SaaS — a visual app builder that compiles to React and connects to any database or API.\n\nSmall team, huge impact. We ship constantly and you'll own features end-to-end.`,
    requirements: [
      '4+ years of full stack development experience',
      'Strong React and TypeScript skills',
      'Solid backend experience with Node.js',
      'Experience with PostgreSQL or similar databases',
      'Comfort with complex codebases and ambiguity',
      'Nice to have: experience with visual programming or low-code tools',
    ],
    tags: ['React', 'Node.js', 'TypeScript', 'Full Stack'],
    matchScore: 89,
    postedDate: '2024-01-07',
    logo: 'R',
    logoColor: 'bg-orange-600',
  },
  {
    id: '14',
    title: 'Machine Learning Engineer',
    company: 'Cohere',
    location: 'Toronto, Canada',
    salary: '$160,000 - $220,000',
    type: 'Hybrid',
    description: `Cohere is building the AI platform for the enterprise and we're looking for ML Engineers to work on training and deploying large language models. You'll work on the core models that power our API used by thousands of developers.\n\nThis is a highly technical role at the frontier of NLP research. You'll implement novel architectures, optimize training pipelines, and ensure our models achieve state-of-the-art performance.\n\nWe're a team of world-class ML researchers and engineers building the future of language AI.`,
    requirements: [
      '4+ years of ML engineering or research experience',
      'Deep knowledge of transformer architectures and NLP',
      'Expert Python and PyTorch skills',
      'Experience training large-scale ML models',
      'Strong math background (linear algebra, statistics, calculus)',
      'Publications or open source contributions in NLP a plus',
    ],
    tags: ['PyTorch', 'NLP', 'LLMs', 'Machine Learning'],
    matchScore: 83,
    postedDate: '2024-01-06',
    logo: 'C',
    logoColor: 'bg-indigo-600',
  },
  {
    id: '15',
    title: 'Product Designer',
    company: 'Loom',
    location: 'San Francisco, CA',
    salary: '$130,000 - $175,000',
    type: 'Hybrid',
    description: `Loom is looking for a Product Designer to work on our video messaging platform used by 25M+ people. You'll design experiences that make async communication feel human and natural.\n\nYou'll own design for core recording and viewing experiences, working closely with engineers and PMs in small, nimble squads. We care about polish and have high craft standards.\n\nRecently acquired by Atlassian, we have startup energy with enterprise resources.`,
    requirements: [
      '4+ years of product design experience',
      'Strong portfolio with shipped consumer or prosumer products',
      'Excellent interaction design and motion design skills',
      'Experience with design systems and component libraries',
      'Ability to work in ambiguity and move quickly',
      'Passion for async-first communication tools',
    ],
    tags: ['Product Design', 'Motion Design', 'Consumer', 'B2B'],
    matchScore: 77,
    postedDate: '2024-01-06',
    logo: 'L',
    logoColor: 'bg-pink-500',
  },
  {
    id: '16',
    title: 'Business Analyst',
    company: 'DoorDash',
    location: 'San Francisco, CA',
    salary: '$90,000 - $125,000',
    type: 'Hybrid',
    description: `DoorDash is hiring a Business Analyst to work on our Merchant Analytics team. You'll help restaurant partners understand their performance on our platform and identify opportunities to grow their business.\n\nYou'll build dashboards, run analyses, and translate data into actionable insights for both internal teams and merchant partners. Strong SQL and stakeholder communication skills are essential.\n\nJoin a mission-driven company empowering local economies.`,
    requirements: [
      '2+ years of business analysis or data analytics experience',
      'Expert SQL skills',
      'Experience with Tableau, Looker, or similar BI tools',
      'Strong business acumen and analytical thinking',
      'Excellent communication and presentation skills',
      'Experience with marketplace businesses a plus',
    ],
    tags: ['SQL', 'Analytics', 'Tableau', 'Marketplace'],
    matchScore: 73,
    postedDate: '2024-01-05',
    logo: 'D',
    logoColor: 'bg-red-500',
  },
  {
    id: '17',
    title: 'Operations Manager',
    company: 'Flexport',
    location: 'Chicago, IL',
    salary: '$95,000 - $130,000',
    type: 'Onsite',
    description: `Flexport is seeking an Operations Manager to lead our Midwest freight operations team. You'll manage a team of 15 operators, oversee daily shipment execution, and drive continuous process improvement.\n\nYou'll work at the intersection of technology and logistics, using our platform to optimize freight movements for hundreds of enterprise customers. This is a high-ownership role in a fast-moving environment.\n\nWe're modernizing global trade and moving fast.`,
    requirements: [
      '4+ years of operations management experience',
      'Experience managing and developing teams of 10+',
      'Strong process improvement and analytical skills',
      'Comfort with technology and data-driven decision making',
      'Experience in logistics, supply chain, or operations preferred',
      'Excellent stakeholder management skills',
    ],
    tags: ['Operations', 'Supply Chain', 'Management', 'Logistics'],
    matchScore: 62,
    postedDate: '2024-01-05',
    logo: 'F',
    logoColor: 'bg-blue-700',
  },
  {
    id: '18',
    title: 'Data Engineer',
    company: 'dbt Labs',
    location: 'Remote',
    salary: '$135,000 - $180,000',
    type: 'Remote',
    description: `dbt Labs is looking for a Data Engineer to work on our cloud data platform used by 50,000+ data teams. You'll build the infrastructure and pipelines that power dbt Cloud and help data teams around the world work more effectively.\n\nYou'll work with Spark, Airflow, and cloud data warehouses (Snowflake, BigQuery, Redshift) at scale. This is a senior technical role with significant ownership.\n\nYou'll be joining the company that created dbt — the most popular data transformation tool in the world.`,
    requirements: [
      '5+ years of data engineering experience',
      'Expert knowledge of dbt (naturally)',
      'Strong Python and SQL skills',
      'Experience with Airflow or similar orchestration',
      'Deep knowledge of cloud data warehouses',
      'Experience with streaming data (Kafka, Flink) a plus',
    ],
    tags: ['dbt', 'Python', 'Spark', 'Data Engineering'],
    matchScore: 86,
    postedDate: '2024-01-04',
    logo: 'D',
    logoColor: 'bg-orange-700',
  },
  {
    id: '19',
    title: 'Cloud Architect',
    company: 'Palantir',
    location: 'New York, NY',
    salary: '$175,000 - $250,000',
    type: 'Onsite',
    description: `Palantir is hiring a Cloud Architect to design and evolve the infrastructure that powers our Foundry and Gotham platforms deployed at the world's most important institutions.\n\nYou'll work with customers' security teams to architect Palantir deployments in government clouds (AWS GovCloud, Azure Government), design network topologies, and ensure compliance with stringent security requirements.\n\nThis role requires both deep technical expertise and the ability to communicate with executive stakeholders.`,
    requirements: [
      '7+ years of cloud architecture experience',
      'AWS Certified Solutions Architect Professional or equivalent',
      'Experience with government cloud environments and compliance (FedRAMP)',
      'Deep expertise in security architecture and zero-trust networking',
      'Experience with Kubernetes and containerized deployments at scale',
      'Secret or Top Secret clearance preferred',
    ],
    tags: ['AWS', 'GovCloud', 'Security', 'Kubernetes'],
    matchScore: 60,
    postedDate: '2024-01-04',
    logo: 'P',
    logoColor: 'bg-gray-600',
  },
  {
    id: '20',
    title: 'Growth Engineer',
    company: 'Webflow',
    location: 'Remote',
    salary: '$140,000 - $185,000',
    type: 'Remote',
    description: `Webflow is hiring a Growth Engineer to work at the intersection of product, data, and marketing. You'll build experiments, optimize conversion funnels, and create personalized experiences that drive signup and activation.\n\nYou'll work across the full funnel — from marketing site performance to in-product onboarding flows. Strong engineering skills plus growth intuition are essential.\n\nWe're helping millions of people build for the web without code.`,
    requirements: [
      '4+ years of engineering experience with growth focus',
      'Strong React/TypeScript and Node.js skills',
      'Experience with A/B testing frameworks and analytics tools',
      'Data-driven mindset with strong SQL skills',
      'Experience optimizing conversion funnels and onboarding',
      'Familiarity with SEO and web performance',
    ],
    tags: ['React', 'Growth', 'A/B Testing', 'Full Stack'],
    matchScore: 87,
    postedDate: '2024-01-03',
    logo: 'W',
    logoColor: 'bg-blue-500',
  },
  {
    id: '21',
    title: 'iOS Engineer',
    company: 'Duolingo',
    location: 'Pittsburgh, PA',
    salary: '$130,000 - $175,000',
    type: 'Hybrid',
    description: `Duolingo is looking for an iOS Engineer to work on our app used by 80M+ daily active learners. You'll build engaging learning experiences that help people achieve their language learning goals.\n\nWe're obsessed with user engagement and learning science. You'll work on features that use gamification, AI, and behavioral psychology to create habit-forming learning flows.\n\nOur iOS app is one of the most technically sophisticated in the App Store.`,
    requirements: [
      '4+ years of iOS development experience',
      'Expert Swift and UIKit/SwiftUI skills',
      'Experience with complex animations and custom UI components',
      'Strong understanding of iOS performance optimization',
      'Experience with offline-first architecture',
      'Passion for education or consumer apps',
    ],
    tags: ['Swift', 'iOS', 'SwiftUI', 'Consumer'],
    matchScore: 81,
    postedDate: '2024-01-03',
    logo: 'D',
    logoColor: 'bg-green-500',
  },
  {
    id: '22',
    title: 'Head of People & Culture',
    company: 'Airtable',
    location: 'San Francisco, CA',
    salary: '$175,000 - $230,000',
    type: 'Hybrid',
    description: `Airtable is seeking a Head of People & Culture to lead our HR function during a critical growth phase. You'll own talent acquisition, total rewards, L&D, and DEI for our 900-person organization.\n\nYou'll partner directly with the executive team to build the people programs that attract, develop, and retain world-class talent. This is a strategic, hands-on role.\n\nWe're building the platform to create the future of work.`,
    requirements: [
      '10+ years of HR/People leadership experience',
      'Experience building People programs at a scaling tech company',
      'Track record of successful DEI initiatives',
      'Strong executive presence and communication skills',
      'Experience with compensation benchmarking and total rewards design',
      'Background in organizational design and change management',
    ],
    tags: ['People', 'HR', 'Leadership', 'Culture'],
    matchScore: 64,
    postedDate: '2024-01-02',
    logo: 'A',
    logoColor: 'bg-yellow-600',
  },
  {
    id: '23',
    title: 'Security Engineer',
    company: 'Cloudflare',
    location: 'Austin, TX',
    salary: '$155,000 - $210,000',
    type: 'Hybrid',
    description: `Cloudflare is hiring a Security Engineer to work on the team that protects our network serving 20% of the internet. You'll build security tooling, conduct threat modeling, and respond to security incidents.\n\nYou'll work on some of the hardest security problems in the industry — defending against nation-state attackers at global scale. Every decision matters.\n\nWe're protecting a better internet for everyone.`,
    requirements: [
      '5+ years of security engineering experience',
      'Deep expertise in network security and protocols',
      'Experience with threat modeling and penetration testing',
      'Strong programming skills (Go, Python, Rust)',
      'Knowledge of TLS, DNS, and internet infrastructure',
      'Experience with SIEM and incident response',
    ],
    tags: ['Security', 'Go', 'Networking', 'Infrastructure'],
    matchScore: 71,
    postedDate: '2024-01-02',
    logo: 'C',
    logoColor: 'bg-orange-500',
  },
  {
    id: '24',
    title: 'Staff Engineer, Infrastructure',
    company: 'Figma',
    location: 'San Francisco, CA',
    salary: '$220,000 - $300,000',
    type: 'Hybrid',
    description: `Figma is looking for a Staff Engineer to lead our Infrastructure team as we scale to support hundreds of millions of users. You'll set technical direction, drive architectural decisions, and mentor senior engineers.\n\nYou'll work on the hardest scaling challenges in our stack — real-time collaboration at scale, global edge delivery, and multi-region reliability. Your decisions will affect every Figma user.\n\nThis is a senior technical leadership role with organization-wide impact.`,
    requirements: [
      '10+ years of software engineering experience',
      '5+ years working on infrastructure or platform engineering',
      'Track record of leading large technical initiatives across teams',
      'Deep expertise in distributed systems and cloud architecture',
      'Experience with real-time systems and WebSockets at scale',
      'Strong mentorship and communication skills',
    ],
    tags: ['Infrastructure', 'Distributed Systems', 'Leadership', 'Scala'],
    matchScore: 78,
    postedDate: '2024-01-01',
    logo: 'F',
    logoColor: 'bg-pink-600',
  },
  {
    id: '25',
    title: 'Technical Recruiter',
    company: 'Scale AI',
    location: 'San Francisco, CA',
    salary: '$90,000 - $130,000',
    type: 'Hybrid',
    description: `Scale AI is hiring a Technical Recruiter to help us grow our engineering and research teams working on AI and data infrastructure. You'll partner with engineering leaders to hire top ML engineers, software engineers, and researchers.\n\nYou'll source creatively, build relationships with passive candidates, and move quickly without sacrificing quality. We're competing for the best AI talent in the world.\n\nJoin us in accelerating the development of AI.`,
    requirements: [
      '3+ years of technical recruiting experience',
      'Track record of hiring senior engineers and ML researchers',
      'Experience with full-cycle recruiting (sourcing through offer)',
      'Comfort with technical concepts to have credible conversations with candidates',
      'Experience using LinkedIn Recruiter and modern sourcing tools',
      'Data-driven approach to recruiting metrics',
    ],
    tags: ['Recruiting', 'AI', 'Talent Acquisition', 'HR'],
    matchScore: 66,
    postedDate: '2024-01-01',
    logo: 'S',
    logoColor: 'bg-indigo-500',
  },
]

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const query = searchParams.get('q')?.toLowerCase()
  const location = searchParams.get('location')?.toLowerCase()
  const type = searchParams.get('type')?.toLowerCase()

  let jobs = [...mockJobs]

  if (query) {
    jobs = jobs.filter(
      (job) =>
        job.title.toLowerCase().includes(query) ||
        job.company.toLowerCase().includes(query) ||
        job.description.toLowerCase().includes(query) ||
        job.tags.some((tag) => tag.toLowerCase().includes(query))
    )
  }

  if (location && location !== 'all') {
    jobs = jobs.filter((job) => job.location.toLowerCase().includes(location))
  }

  if (type && type !== 'all') {
    jobs = jobs.filter((job) => job.type.toLowerCase() === type.toLowerCase())
  }

  return NextResponse.json(jobs)
}
